### ISSUE TITLE
Joining forces

### ISSUE THREAD

**Issue by ramnes** [thrau/notion-objects#2]
Hey Thomas, Guillaume here (author of notion-sdk-py).

Cool project that you've started building! I'm really eager to see a higher-level library emerge on top of notion-sdk-py.

There's also [notional](https://github.com/jheddings/notional) that has the same goal, did you see that library before starting to build notion-object? If so, what was your rationale for starting over? If not, would it make sense to join forces?

cc @jheddings

**Comment by thrau** [comment]
Hey @ramnes, I wasn't aware of notional, thanks for the hint! I started building notion-objects for fun and for the use in an ETL job we needed to get data from notion into a different database. I didn't do a super thorough search on alternatives, it was basicaly done in a coffee-fuled weekend :-)

Looks like notional is more mature than notion-objects, and looks like the object API idea is pretty much the same. My biggest requirement is to be able to plug in custom property transformers, if notional supports that, then I don't see a reason to continue development of notion-objects.

I don't know what joining forces would mean at this point, other than abandoning notion-objects in favor of notional, since it's clearly further along as a project. Or are you looking into extending notion-sdk-py with a higher-level API?

**Comment by jheddings** [comment]
Hi @thrau !  Author of Notional here...

The object model for Notional is definitely in need of some work.  I would welcome the collaboration if you wanted to incorporate features from `notion-objects`, but I also understand that it may be faster for your needs to keep them separate.  In either case, I'd like to spend some time digging into custom property transformers when I have the chance.

**Comment by ramnes** [comment]
> I don't know what joining forces would mean at this point, other than abandoning notion-objects in favor of notional, since it's clearly further along as a project. Or are you looking into extending notion-sdk-py with a higher-level API?

I'm not looking to extend notion-sdk-py for now, just trying to gather contributors for a common effort into an higher level library. :)

**Comment by fuschini** [comment]
On the note of joining forces, is there anything like these libraries for the Notion Javascript SDK?

I was doing some research and only found these Python libs

**Comment by thrau** [comment]
I've decided to continue developing notion-objects. The APIs of notion-objects and notional are diverging quite a bit now, and I find it easier to bring in my own ideas and concepts into my own library than someone elses.

sorry @fuschini, I'm not familiar enough with the Javascript ecosystem to say.
